services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=1p@ssw0rd
      - POSTGRES_USER=supakorn
      - POSTGRES_DB=supakorn

  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=supakorn-bo@rmutp.ac.th
      - PGADMIN_DEFAULT_PASSWORD=1p@ssw0rd